dat_shell:		error.o makeargv.o dat_shell.o
				gcc -g error.o makeargv.o dat_shell.o -o dat_shell
				./dat_shell
				
dat_shell.o:	dat_shell.c
				gcc -c dat_shell.c
				
makeargv.o:		makeargv.c
				gcc -c makeargv.c

error.o:		error.c
				gcc -c error.c
