/* Generated By:JavaCC: Do not edit this line. CalcParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalcParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WITH = 5;
  /** RegularExpression Id. */
  int CEIL = 6;
  /** RegularExpression Id. */
  int EXP = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int MINUS = 9;
  /** RegularExpression Id. */
  int MULTIPLY = 10;
  /** RegularExpression Id. */
  int DIVIDE = 11;
  /** RegularExpression Id. */
  int LP = 12;
  /** RegularExpression Id. */
  int RP = 13;
  /** RegularExpression Id. */
  int LBK = 14;
  /** RegularExpression Id. */
  int RBK = 15;
  /** RegularExpression Id. */
  int LB = 16;
  /** RegularExpression Id. */
  int RB = 17;
  /** RegularExpression Id. */
  int COMMA = 18;
  /** RegularExpression Id. */
  int NUM = 19;
  /** RegularExpression Id. */
  int DIGIT = 20;
  /** RegularExpression Id. */
  int ALPHA = 21;
  /** RegularExpression Id. */
  int ID = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"with\"",
    "\"ceil\"",
    "\"exp\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "<NUM>",
    "<DIGIT>",
    "<ALPHA>",
    "<ID>",
  };

}
